# Docker Compose Simplificado para Desenvolvimento
# Use: docker-compose -f docker-compose.simple.yml up

services:
  # Apenas PostgreSQL para desenvolvimento local
  db:
    image: postgres:15-alpine
    container_name: dev_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: empresas_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_dev: