services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=empresas_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/empresas_db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python scripts/wait_for_db.py && python scripts/seed_postgres.py && uvicorn app.main:app --host 0.0.0.0 --port 8000"

volumes:
  db_data:
